version: "3.8"

services:
  app:
    # Mengambil hasil build Jenkins dari Docker Hub
    image: ichsan06/washkita-app:latest 
    container_name: laundry-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - laundry-network
    # .env diletakkan manual di VPS atau diinject Jenkins
    env_file:
      - .env 

  nginx:
    image: nginx:alpine
    container_name: laundry-nginx
    restart: unless-stopped
    ports:
      - "8006:80" # Biasanya VPS pakai port 80/443 standar
    volumes:
      # Nginx hanya butuh config, kode sudah ada di dalam image 'app'
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laundry-network

  mysql:
    image: mysql:8.0
    container_name: laundry-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    # Port MySQL sebaiknya tidak dibuka ke publik (hapus ports jika tidak perlu remote)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laundry-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laundry-phpmyadmin
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - laundry-network

volumes:
  mysql_data:

networks:
  laundry-network:
    driver: bridge

